// Search
export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const authConstants = {
    // SignUp
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE_DUPLICATE_USERNAME: "SIGNUP_FAILURE_DUPLICATE_USERNAME",
    SIGNUP_FAILURE_DUPLICATE_EMAIL: "SIGNUP_FAILURE_DUPLICATE_EMAIL",

    // Signin
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAILURE_USER_NOT_EXIST: "SIGNIN_FAILURE_USER_NOT_EXIST",
    SGININ_FAILURE_WRONG_PW: "SIGNIN_FAILURE_WRONG_PW",

    // Signout
    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    SIGNOUT_FAILURE: "SIGNOUT_FAILURE",
};

export const paperConstants = {
    // GetPaper
    GET_PAPER_SUCCESS: "GET_PAPER_SUCCESS",
    GET_PAPER_FAILURE: "GET_PAPER_FAILURE",
};
