# Generated by Django 2.2.5 on 2019-10-31 17:36

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('researcher_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'swpp_author',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'swpp_keyword',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('title', models.CharField(max_length=400)),
                ('language', models.CharField(max_length=20)),
                ('abstract', models.TextField(max_length=5000)),
                ('ISSN', models.CharField(max_length=20)),
                ('eISSN', models.CharField(max_length=20)),
                ('DOI', models.CharField(max_length=40)),
                ('file_url', models.URLField()),
                ('download_url', models.URLField()),
            ],
            options={
                'db_table': 'swpp_paper',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='PaperPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('volume', models.CharField(max_length=20, null=True)),
                ('issue', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True, verbose_name='date paper was published')),
                ('beginning_page', models.PositiveIntegerField(null=True)),
                ('ending_page', models.PositiveIntegerField(null=True)),
                ('ISBN', models.CharField(max_length=20)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papersfeed.Paper')),
            ],
            options={
                'db_table': 'swpp_paper_publication',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'swpp_publisher',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('username', models.CharField(default=None, max_length=21, unique=True)),
                ('description', models.TextField(default=None, null=True)),
                ('email', models.CharField(default=None, max_length=190, null=True, unique=True)),
                ('password', models.TextField(default=None, null=True)),
                ('salt', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'swpp_user',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('followed_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_followed_user', to='papersfeed.User')),
                ('following_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_following_user', to='papersfeed.User')),
            ],
            options={
                'db_table': 'swpp_user_follow',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('referenced_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_paper', to='papersfeed.Paper')),
                ('referencing_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_paper', to='papersfeed.Paper')),
            ],
            options={
                'db_table': 'swpp_reference',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('name', models.CharField(max_length=200)),
                ('publication_type', django_mysql.models.EnumField(choices=[('journal', 'journal'), ('book', 'book'), ('series', 'series'), ('patent', 'patent')])),
                ('papers', models.ManyToManyField(through='papersfeed.PaperPublication', to='papersfeed.Paper')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papersfeed.Publisher')),
            ],
            options={
                'db_table': 'swpp_publication',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='paperpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papersfeed.Publication'),
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('keyword_type', django_mysql.models.EnumField(choices=[('author', 'author'), ('web', 'web'), ('abstract', 'abstract')])),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papersfeed.Keyword')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papersfeed.Paper')),
            ],
            options={
                'db_table': 'swpp_paper_keyword',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('author_type', django_mysql.models.EnumField(choices=[('general', 'general'), ('corresponding', 'corresponding')])),
                ('rank', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papersfeed.Author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papersfeed.Paper')),
            ],
            options={
                'db_table': 'swpp_paper_author',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='references',
            field=models.ManyToManyField(through='papersfeed.Reference', to='papersfeed.Paper'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='papers',
            field=models.ManyToManyField(through='papersfeed.PaperKeyword', to='papersfeed.Paper'),
        ),
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(through='papersfeed.PaperAuthor', to='papersfeed.Paper'),
        ),
    ]
