# Generated by Django 2.2.5 on 2019-10-31 18:23

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0002_auto_20191031_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('type', django_mysql.models.EnumField(choices=[('owner', 'owner'), ('member', 'member')])),
                ('collection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection_user_collection', to='papersfeed.Collection')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection_user_user', to='papersfeed.User')),
            ],
            options={
                'db_table': 'swpp_collection_user',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('collection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection_paper_collection', to='papersfeed.Collection')),
                ('paper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection_paper_paper', to='papersfeed.Paper')),
            ],
            options={
                'db_table': 'swpp_collection_paper',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CollectionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('collection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection_like_collection', to='papersfeed.Collection')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection_like_user', to='papersfeed.User')),
            ],
            options={
                'db_table': 'swpp_collection_like',
                'ordering': ['-pk'],
            },
        ),
    ]
