# Generated by Django 2.2.5 on 2019-11-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0003_collectionlike_collectionpaper_collectionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_paper', to='papersfeed.Paper'),
        ),
    ]
