# Generated by Django 2.2.5 on 2019-11-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0004_review_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewPaper',
        ),
    ]
