# Generated by Django 2.2.5 on 2019-11-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('rank', models.PositiveIntegerField()),
                ('paper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendation_paper', to='papersfeed.Paper')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendation_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_user_recommendation',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('type', django_mysql.models.EnumField(choices=[('collection', 'collection'), ('like', 'like'), ('review', 'review')])),
                ('count', models.IntegerField()),
                ('paper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_action_paper', to='papersfeed.Paper')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_action_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_user_action',
                'ordering': ['-pk'],
            },
        ),
    ]
