# Generated by Django 2.2.5 on 2019-11-26 12:20

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0007_useraction_userrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='type',
            field=django_mysql.models.EnumField(choices=[('add_to_collection', 'add_to_collection'), ('like_paper', 'like_paper'), ('make_review', 'make_review')]),
        ),
    ]
