# Generated by Django 2.2.5 on 2019-11-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0008_auto_20191126_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='source',
            field=models.CharField(default='arxiv', max_length=50),
        ),
    ]
