# Generated by Django 2.2.5 on 2019-11-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0009_paper_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
