# Generated by Django 2.2.5 on 2019-11-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0009_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='recipient_user_id',
        ),
    ]
