# Generated by Django 2.2.5 on 2019-12-04 16:02

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0010_subscription_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='type',
            field=django_mysql.models.EnumField(choices=[('public', 'public'), ('private', 'private')], default='public'),
        ),
    ]
