# Generated by Django 2.2.5 on 2019-12-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papersfeed', '0011_collection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
