# Generated by Django 2.2.5 on 2019-10-23 07:31

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('researcher_id', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=20)),
                ('abstract', models.TextField(max_length=5000)),
                ('ISSN', models.DecimalField(decimal_places=10, max_digits=19)),
                ('eISSN', models.DecimalField(decimal_places=10, max_digits=19)),
                ('DOI', models.DecimalField(decimal_places=10, max_digits=19)),
                ('file_url', models.URLField()),
                ('download_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenced_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_paper', to='papers.Paper')),
                ('referencing_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_paper', to='papers.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publication_type', django_mysql.models.EnumField(choices=[('journal', 'journal')])),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='PaperPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField()),
                ('issue', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='time paper was published')),
                ('beginning_page', models.PositiveIntegerField()),
                ('ending_page', models.PositiveIntegerField()),
                ('ISSN', models.DecimalField(decimal_places=10, max_digits=19)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Paper')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_type', django_mysql.models.EnumField(choices=[('author', 'author'), ('web', 'web'), ('abstract', 'abstract')])),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Keyword')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', django_mysql.models.EnumField(choices=[('general', 'general'), ('corresponding', 'corresponding')])),
                ('rank', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Paper')),
            ],
        ),
    ]
